### PR TITLE
[11ty] - Schedule appointment

### PR DESCRIPTION
**Pull request by mejiaj**
Use new 11ty build for schedule appointment test and update to USWDS 3.3.0

### CODE REVIEW

**Review by thisisdano — APPROVED** [review]

**Comment by mejiaj** [comment]
@thisisdano we could wait to see if Snyk detects the new build or try deactivating/reactivate. It's odd that it's still referencing `master` branch when that was renamed. 

Poking around the Snyk settings I see this error:
image

**Review by thisisdano — APPROVED** [review]
Working again

**Comment by thisisdano** [comment]
OK, I've removed the `gemfile.lock` job from Snyk and we shouldn't see these errors going forward

**Comment by mejiaj** [comment]
@jonathanbobel I've pulled in latest changes from your branch. Can you please take a look?

[Preview link →](https://federalist-d5e7c07c-6ffa-4b8e-935f-49a7df24a505.sites.pages.cloud.gov/preview/uswds/uswds-sandbox/jm-eleventy-schedule-appointment/)

Luckily page builds are down to a minute (previously 4min).

**Pull request merged**
