### PR TITLE
Update to newest USWDS and resolve vuln from npm audit

### LINKED ISSUE #8: Jekyll runtime error when attempting to serve locally
## Issue
Upon running `bundle exec jekyll serve,` the process fails after apparently encountering a conversion error in `/node_modules/uswds/dist/scss`. 

## Error message
`Conversion error: Jekyll::Converters::Scss encountered an error while converting 'assets/css/main.scss':
                    $string: #0000ff is not a string for 'quote' on line 106`

## Efforts to debug
Unable to pinpoint the location of `quote` via text search or browsing. Not sure where this error in the code is presenting itself

## Reproducibility
Have attempted to deploy with Siteleaf and Cloudcannon; both efforts fail, citing the same issue in the error logs.

### PR DESCRIPTION
**Pull request by thisisdano**
fixes #8

### CODE REVIEW

**Comment by maya** [comment]
@thisisdano I tried to upgrade ffi to the version it told me in to in #11 when following the error warning link, this got the Snyk error to go away, but it caused a Federalist build error. Maybe @el-mapache has some ideas.

**Comment by maya** [comment]
Link to issue and where it was introduced: https://snyk.io/org/uswds/test/github/4e925358-1747-4e81-8c9d-0b6ecafa1d50/master..3677ec99432ada8a33cfb7f62339b06601c11c9d?fromStatus=true

**Comment by maya** [comment]
Do we know if this was fixed in a newer version of jekyll, e.g. Jekyll 3.8.3?

**Comment by thisisdano** [comment]
I don't know if newer a jekyll addresses this, but maybe worth a shot

**Comment by maya** [comment]
@thisisdano not sure how to resolve the Snyk error either, maybe we should just merge and ignore it?

**Comment by el-mapache** [comment]
@maya did you try updating the jekyll version? Its unlikely that a DLL issue will cause problems with our envs, but I suppose it might be bad for windows users who are also trying to use this repo?

**Comment by maya** [comment]
@el-mapache I didn't bc when I checked the dependencies that were causing issues on the newer Jekyll, they were the same.

**Comment by maya** [comment]
@uswds/core This is fixed once #13 is merged in 🎉

**Pull request merged**
